### ISSUE TITLE
Weird lines/missing @ in WASM versions of RLTK games

### ISSUE THREAD

**Issue by workingjubilee** [thebracket/bracket-lib#102]
So, about when I started playing another user of RLTK's game via their to-WASM compilation, I finally realized something was up. On my Arch computer, I get this weird issue of blank spaces being filled with lines and my "@" not displaying on the WASM versions of RLTK games, but NOT on my local compilations that I run, where everything displays fine. Seeing as how it's an Arch installation, and I tried on an Ubuntu box and that worked (it displayed akin to what I would expect on the local compilation on my Arch box), I am totally willing to believe it's "my fault", but I am offering this issue so that it can be documented, fixed, and future hapless Linux users may have something to refer to.

Browser: Mozilla Firefox.

![image](https://user-images.githubusercontent.com/46493976/76689611-de0c6000-65f4-11ea-8714-b3c88b1885b6.png)

**Comment by thebracket** [comment]
That's very odd! I don't have an Arch setup to test with, but it sure looks like texture filtering. If I change the mag/min filters in GL to something other than "nearest" - that's what you get (in an attempt to make it look better, the filter reads neighboring pixels even though they are outside of the glyph; the result can be really nasty - and looks a lot like that).

I'll see what I can find.

**Comment by thebracket** [comment]
I've updated the web examples to the current unified GL backend (it's pretty much a rewrite; WebGL and native now use the same code path, and there's error handling everywhere). Do you get the same issue with http://bfnightly.bracketproductions.com/wasmtest/sparse/ ?

**Comment by workingjubilee** [comment]
Ah, much better yes!
![image](https://user-images.githubusercontent.com/46493976/78088248-6e2e0180-7378-11ea-9dbd-df3e3dfc0f54.png)

**Comment by thebracket** [comment]
Awesome. I have a couple of issues left to fix, and then the tutorial will be updated for the latest release. It should fix a lot of issues including this one.
