### ISSUE TITLE
access to dpi_scale_factor

### ISSUE THREAD

**Issue by jice-nospam** [thebracket/bracket-lib#105]
I still have an issue with mouse coordinates on hidpi screens when `with_automatic_console_resize` is false.
doryen-rs provides f32 console cell mouse coordinates. I need to compute them from bracketlib's `mouse_pixel_pos` and for that I need the dpi_scale_factor.

When `with_automatic_console_resize` is true, I get this factor on the first resize event but when it's false, no resize event is sent.

I think in a more general way, it would be nice to make this value available to the end user, for example though `ctx.dpi_scale_factor`

**Comment by thebracket** [comment]
There's actually two issues in one here:

* The mouse pixel position available via `input.mouse_pixel_pos()` really should be scaled to take into account high DPI anyway.
* It's a good idea to offer the `scale_factor`, but it will always be 1.0 on back-ends other than native GL.

There's two commits about to hit that provide both of those.

**Comment by jice-nospam** [comment]
nice :) Now it works out of the box at start, but if I resize the window, the console is scaled and it's broken again because I can't be aware that the screen size has changed.
I think bracketlib should send Resized event even when `with_automatic_console_resize` is false. This way the end user can be informed that the char size has changed even though the console size is the same. You removed this event because doryen-rs was systematically resizing the console but it was rather an issue in doryen-rs.

**Comment by jice-nospam** [comment]
ok it seems all cases are working on native target. now to the web target... :)
