### ISSUE TITLE
Suggestion: more mouse functionality (pressed, released)

### ISSUE THREAD

**Issue by Maxgy** [thebracket/bracket-lib#107]
As of now, one can get the position of the mouse and whether or not it was clicked or released. The problem is, there's no functionality to distinguish between a mouse release and a mouse press, which means there also isn't a way to see if the mouse is being held or not. It would be useful to have this added along with the ability to hide the cursor, too.

**Comment by thebracket** [comment]
That should take care of up/down events (check the `input_harness` example for the extended IO system; documentation isn't written yet). The other half of the issue - hiding/showing mouse cursor is harder than it sounds, but I'll take a look. I think it'll be native GL only.

**Comment by thebracket** [comment]
Having looked at it, I can't see a reasonable way to do cursor hiding with Glutin right now. I'm going to close this issue since the events are handled; feel free to make another one for cursor hiding, but it may have to wait for glutin/winit to update.
