### ISSUE TITLE
OpenGL renderer glitches on window scale (MacOS, retina)

### ISSUE THREAD

**Issue by ytaras** [thebracket/bracket-lib#109]
If I try to run simple example (using default OpenGL renderer) and try to resize game window, it acts weird. With original size render area take 100% of the window. If I shrink window vertically, render area shrinks non in proportion, leaving some of the window blank. On the other hand, if I resize window to be larger, drawing area doesn't fit into window. Same happens to horizontal scaling.
I think is caused by retina display on my laptop, as I've seen other issues in tracker related to hdpi display. 
Here's an example of drawing 80x50 red area and resizing a window: 
<img width="752" alt="Screenshot 2020-03-31 at 11 47 35" src="https://user-images.githubusercontent.com/221503/78006266-6e60d980-7345-11ea-892b-e4be2e47a17e.png">

Source code for example:
<details>

```rust
use bracket_lib::prelude::*;
struct State {
}

impl GameState for State {
    fn tick(&mut self, ctx: &mut BTerm) {
        ctx.cls();
        ctx.fill_region(Rect::with_size(0, 0, 80, 50), ' ' as u8, RGB::named(BLACK), RGB::named(RED));
    }
}
fn main()  {
    let context = BTermBuilder::simple80x50()
        .with_title("Hello RLTK World")
        .build();
    let gs: State = State {
    };

    main_loop(context, gs)
}

```
</details>

**Comment by ytaras** [comment]
Have just verified same issue with latest (master) version of code

**Comment by thebracket** [comment]
I wish I had a Mac to test on; I can't get the same results on Windows or Linux messing with display scaling. Does it also do that on the included examples?

**Comment by ytaras** [comment]
Unfortunately it does. 
If that helps - it works even for native_gl example, including custom-drawn triangle:
![out](https://user-images.githubusercontent.com/221503/78128484-b30c7380-741e-11ea-8a97-7faf9e65dedb.gif)

**Comment by djmittens** [comment]
I am also affected by this plague, is there any workarounds?

**Comment by thebracket** [comment]
Oh no, I thought this was fixed. Are you using the crate or the github version? I don't have a Mac to test on, but I'll see what I can do.

**Comment by djmittens** [comment]
I am following the rogue like tutorial and i am using the following version of rltk:
```
[dependencies]
rltk = "0.8.1"
```

**Comment by garritfra** [comment]
Just checking in to see if there's any progress on this? I've got the same issue, but I'm glad that it only seems to affect MacOS.

**Comment by singalen** [comment]
I tried debugging it, but didn't get very far, as my Rust is very basic.
Would love to get some clue where to look.

**Comment by thebracket** [comment]
Just getting back into the swing of things after being unwell and then having to care for my mother being unwell. It does look like a DPI issue, I have a few ideas - I'll do some digging and post results. Trying to avoid having to buy a Mac to test with!

**Comment by singalen** [comment]
Happy to help to diagnose it, I run into it each time. I also cannot build bracket-lib with Metal (#188).
Hope you family gets well.

**Comment by thebracket** [comment]
Now *that's* interesting. Updating glutin and winit has given me similar behavior on Windows! It looks like when `PhysicalSize` returns now, it already has the scale factor applied to it. I just tested on Windows, and removing the dpi_size division was required to make it work properly. I'm testing that in a Linux VM.

**Comment by thebracket** [comment]
I just committed the code that gives sensible behavior on Windows and Ubuntu/X11. Would someone mind giving this a go on a Mac for me, please?

**Comment by singalen** [comment]
It got much better now, thank you!
The default size is spot on (before it had offset on the left and was off the window on the right), but resize still misbehaves a bit.
![bracket-mac](https://user-images.githubusercontent.com/151199/107426337-ed31b180-6ad4-11eb-875f-e8ad87c40337.gif)

**Comment by thebracket** [comment]
That's progress. :-) I suspect I can find a couple of other uses of DPI that are causing that issue. I'll go digging in a minute. (The bouncy gif is trippy!)

**Comment by thebracket** [comment]
Found the downside of the above fix - it messes up mouse position calculation after the window is resized. I think I know how to get this fixed, though - it may be tomorrow, I'm running short of time for the day. Thanks for the help - I'm pretty sure I've narrowed it down.

**Comment by thebracket** [comment]
Ok, I've taken the changes that helped earlier and gone a little further with them - and completely rewritten the mouse positioning section. This *should* help with the scaling issues. On my Ubuntu/X11 and Windows installations it's dead on the money both initially and after a resize on various scaling settings (tested 125%, 150%, 200%). So I'm really hopeful that this will help with the OS X issues.

**Comment by singalen** [comment]
Thank you very much!
Will try the mouse as soon as I can. So far, resizing the window still messes up the scale like on the image before 8(

**Comment by thebracket** [comment]
Progress! I found someone else who had suffered a similar problem, and applied their fix. Turned out to be two lines of code! It now scales correctly on everything I have available to test with - Windows, Ubuntu 20.1/X11, Ubuntu 20.1/Wayland. That's the first time Wayland has look right in a few `winit` releases, which is a good sign. :-)

**Comment by thebracket** [comment]
A friend (Red blob games on the roguelikedev discord) informs me that it is working really well on his Mac now. :-)

**Comment by thebracket** [comment]
I've now had two people tell me that this is working correctly now. So I'm closing this issue - please re-open if the plague returns!
