### ISSUE TITLE
Black screen with tutorial on sway

### ISSUE THREAD

**Issue by AndreasBackx** [thebracket/bracket-lib#112]
I wanted to get started with the Rust book you wrote, thank you very much for this btw. :heart: Unfortunately I cannot seem to get it to display anything, it simply shows a black screen.

![Screenshot](https://i.imgur.com/OwH544J.jpg)

I assume this has something to do with me using [Sway](https://swaywm.org/) which uses Wayland? As you can see in the screenshot, it has some weird behaviour with regards to that padding. Strange, but I can let it slide. I would love to help, but I was trying to learn some more Rust so I don't think I'll be able to help much besides providing all of the information I can. Let me know if you need any more information.

Rust version: 1.42.0
Rltk version: 0.7.0

**Comment by zaszi** [comment]
Can confirm this is also happening to me with my own project, also on Sway. Rendering with Vulkan and Curses works fine, so this seems to be a problem with just OpenGL on Sway/Wayland. I'm not entirely sure where to start troubleshooting from there, though.

**Comment by AndreasBackx** [comment]
> Can confirm this is also happening to me with my own project, also on Sway. Rendering with Vulkan and Curses works fine, so this seems to be a problem with just OpenGL on Sway/Wayland. I'm not entirely sure where to start troubleshooting from there, though.

Afaik I'm using Vulkan atm though.

Forcing it to use XWayland does fix the problem. You can do this by passing `WINIT_UNIX_BACKEND=x11`.

**Comment by thebracket** [comment]
I've had no end of problems with Wayland support, mostly relating to scaling. `winit` seems to have issues with it; stuff has been randomly breaking on the last few releases. :-( Unfortunately, Googling around I mostly find other people with the same problems.

I'll add a workaround to force Wayland to use the X11 back-end without needing to set environment variables.

**Comment by thebracket** [comment]
With the fix applied, it seems to work on Sway in a VM for me:
![image](https://user-images.githubusercontent.com/14896751/78789437-c2397700-7972-11ea-8de4-81c1f09be5ff.png)

**Comment by zaszi** [comment]
That fixed it for me. Thanks!

**Comment by AndreasBackx** [comment]
This should be fine for now. However this will cause scaling problems for hidpi displays in Sway because Sway does not fix scaling for XWayland apps unfortunately and the maintainer refuses to make a workaround for it.

**Comment by thebracket** [comment]
Sadly, there's not a lot I can do about that. Wayland scaling via `winit` is a mess also. Wayland supports scaling like 1.25 - but it's an integer in the `winit` code!

**Comment by AndreasBackx** [comment]
I'm glad I'm not using any hidpi displays except at work, but luckily working from home in these times.
