### ISSUE TITLE
set_bg doesn't appear to be working when compiling to Wasm

### ISSUE THREAD

**Issue by tylervipond** [thebracket/bracket-lib#113]
`ctx.set_bg` doesn't appear to do anything when I compile a game to wasm and run it in the browser. For an example see the wasm app from this chapter of the tutorial: https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-10-ranged/

Rltk: 0.7.0
Rust: 1.42.0
OS: OSX 10.15.1
Browser: Firefox 74.0, Chrome 80.0.3987.149

**Comment by thebracket** [comment]
I'll double-check, but I believe that has been fixed in the current master of RLTK/bracket-lib. I have a few more things to stabilize before it becomes the crate release (including I need to update initialization in the tutorial versions).

**Comment by thebracket** [comment]
Here we go: the walking example has been updated to use `set_bg` to leave a trail. Works in WASM now: http://bfnightly.bracketproductions.com/wasmtest/walking/

Thanks! Glad this is one I'd already found. :-)

**Comment by tylervipond** [comment]
Great! do you recommend switching to use master as a dependency for the time being? are there any breaking changes?

**Comment by thebracket** [comment]
I'll be updating the tutorial very soon (hopefully today). There is one breaking change, the initialization setup now uses Rust's `Result` system for error handling.
