### ISSUE TITLE
GL initialized logged on every start

### ISSUE THREAD

**Issue by smokku** [thebracket/bracket-lib#115]
How can I disable this log: https://github.com/thebracket/bracket-lib/blob/b12f11163eed052fdad6bdda52cc2f4da861a9ae/bracket-terminal/src/hal/gl_common/font.rs#L67 ?

I don't want my application to log anything unless I explicitly enable logging.

**Comment by thebracket** [comment]
That's a bug; was meant to be removed (it was helping me debug some issues). I'll see about removing it.

**Comment by thebracket** [comment]
I've removed the offending lines.
