### ISSUE TITLE
Sparse Console is not cleared on .cls()

### ISSUE THREAD

**Issue by ytaras** [thebracket/bracket-lib#117]
Steps to reproduce:

1. Create context with main and sparse console
2. Draw something on sparse console
3. Next frame clean sparse console and draw something on main console

Expected behaviour:

 - Only main console is shown, as sparse is clean

Observed behaviour:

 - Latest content of sparse console is shown over main console content

Workaround:

 - Draw some empty transparent char in sparse console after clearing it

<details>
  <summary>Reproducible example</summary>

```rust
use bracket_lib::prelude::{main_loop, BTerm, BTermBuilder, GameState, VirtualKeyCode, RGBA};

const USE_WORKAROUND: bool = false;
fn main() {
    let context = BTermBuilder::simple80x50()
        .with_font("vga8x16.png", 8, 16)
        .with_tile_dimensions(16, 16)
        .with_sparse_console(80, 25, "vga8x16.png")
        .build()
        .unwrap();

    main_loop(
        context,
        Demo {
            show_outer_console: false,
        },
    )
    .unwrap();
}

struct Demo {
    show_outer_console: bool,
}

impl GameState for Demo {
    fn tick(&mut self, ctx: &mut BTerm) {
        ctx.set_active_console(0);
        ctx.cls();
        ctx.print_centered(0, "Main console - overlapping text");

        if self.show_outer_console {
            ctx.set_active_console(1);
            ctx.cls();
            ctx.print_centered(0, "Sparse console");
        }

        match ctx.key {
            Some(VirtualKeyCode::Space) => {
                if self.show_outer_console {
                    ctx.set_active_console(1);
                    ctx.cls();

                    if USE_WORKAROUND {
                        let transparent = RGBA::from_f32(0., 0., 0., 0.);
                        ctx.set(40, 0, transparent, transparent, ' ' as u16);
                    }
                }
                self.show_outer_console = !self.show_outer_console
            }
            _ => (),
        }
    }
}
```  
</details>

**Comment by ytaras** [comment]
Potential fix: 

```
Index: bracket-terminal/src/hal/gl_common/backing/sparse_console_backing.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- bracket-terminal/src/hal/gl_common/backing/sparse_console_backing.rs	(revision 6c6f2f9f1200d548d977a9a9150d670caa76022d)
+++ bracket-terminal/src/hal/gl_common/backing/sparse_console_backing.rs	(date 1587457922865)
@@ -59,9 +59,6 @@
         tiles: &[SparseTile],
         font_dimensions_glyphs: (u32, u32),
     ) {
-        if tiles.is_empty() {
-            return;
-        }
 
         self.vao.vertex_buffer.clear();
         self.vao.index_buffer.clear();
```

It's working, but I guess there's a reason why this code was there in the first place, maybe performance considerations? 

Also I've noticed that console has `is_dirty` flag, which is set to true in multiple places, but I haven't found where it's being set to false. Is it a bug?

**Comment by thebracket** [comment]
Digging through some old code, it looks like you found the issue - and that was meant to be deleted. It was a hangover from trying to fix something else that was left in there by mistake.

You're right, `is_dirty` is a mess! I've started cleaning it up. Thanks for pointing that out.

**Comment by butitsnotme** [comment]
This fixes the issue for me. However a very similar issue exists for the sprite console. It appears that there is a [similar check in its `rebuild_vertices` function](https://github.com/thebracket/bracket-lib/blob/master/bracket-terminal/src/hal/gl_common/backing/sprite_console_backing.rs#L62-L65) I have opened #157 with a fix for this issue.
