### ISSUE TITLE
Sprite/Tilemap Scaling Issues on Windows 10

### ISSUE THREAD

**Issue by DrMelon** [thebracket/bracket-lib#118]
Hello there,
I have been following the excellent tutorial that accompanies this library for some time now, and started branching out and making some of my own changes to get a feel for things. However, while changing the tileset, I have run into an issue on Windows 10; the scale of the window is ever so slightly off, resulting in artifacting when displaying the tileset. 
See the image attached here for an example:
https://i.imgur.com/tmB4a9w.png
Note the orange `%` glyph appears slightly distorted.
https://i.imgur.com/7FzxUSC.png
Scaling up the window by a few pixels (by my count, about 7) seems to resolve the issue, as seen here.

I believe I have seen this issue before when I was working with a different game engine; the process that is setting the size of the window needs to add a couple of extra pixels to account for Windows 10's ultra-thin window borders. There's something wonky somewhere in the WinAPI that prevents the size from being calculated properly: https://stackoverflow.com/questions/34139450/getwindowrect-returns-a-size-including-invisible-borders

**Comment by DrMelon** [comment]
Update on this; it seems to have stopped happening. Possibly one of the libraries that bracket-lib depends on has updated to account for it?

**Comment by thebracket** [comment]
I'm pretty sure that this was fixed upstream. Thanks!
