### ISSUE TITLE
Crash on minimize window

### ISSUE THREAD

**Issue by smokku** [thebracket/bracket-lib#123]
OS Name:                   Microsoft Windows 10 Home
    OS Version:                10.0.18363 N/A Build 18363

When I minimize app window, process panics.

```sh
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target\debug\rust_roguelike_tutorial.exe`
thread 'main' panicked at '[GL] Error: INVALID_ENUM', C:\Users\smoku\.cargo\registry\src\github.com-1ecc6299db9ec823\bracket-terminal-0.8.1\src\hal\gl_common\glerror.rs:25:52
```

**Comment by smokku** [comment]
Works fine on Linux though.

**Comment by thebracket** [comment]
It turns out that Windows sets the inner size to 0 when you minimize, which messes up all the buffer calls. Added a check to make sure it doesn't try and run the game loop while it's impossible to render.

**Comment by thebracket** [comment]
I've verified that the tutorial no longer crashes when minimized on a couple of systems, so I'm closing this issue now.
