### ISSUE TITLE
Documentation suggestion for `get_available_exits`

### ISSUE THREAD

**Issue by atamis** [thebracket/bracket-lib#128]
So, I'll be the first to admit that I'm pretty dumb and probably should have noticed this. However, it may be helpful to people as dumb as me to state this assumption directly in the documentation `BaseMap::get_available_exits`.

Basically, it looks like `a_star_search` assumes that `get_available_exits` will never return the parameter. That is, `get_available_exits` should never offer "standing still" as a possible exit. If you do, however, `a_star_search` will never terminate: it will get stuck in an infinite loop. Specifically, in the code

```rust
    /// Helper function to unwrap a path once we've found the end-point.
    fn found_it(&self) -> NavigationPath {
        let mut result = NavigationPath::new();
        result.success = true;
        result.destination = self.end;

        result.steps.push(self.end);
        let mut current = self.end;
        while current != self.start {
            let parent = self.parents[&current];
            result.steps.insert(0, parent);
            current = parent;
        }

        result
    }
```

The first tile (I think, I'm not sure which tile this fails on) essentially forms a self loop because its parent is itself, so `current` never changes and it keeps getting inserted into `result.steps`. Because A* doesn't form loops by design, `found_it` is unprepared to deal with loops and never terminates, filling `result.steps` with copies of the same index.

This took me a long time to debug and I had to break out GDB and try out a lot of stuff to figure it out. I know it's dumb to return the current tile from the exits (as it isn't an exit), but I didn't think it'd be a big deal to the algorithm because "exiting" to the same tile will never get you anywhere.

Especially with functions that users are expected to implement, stating all the assumptions about a function is a good idea.

Thanks for all the work you do on the library.

**Comment by thebracket** [comment]
I believe I fixed this a while ago and forgot to close the issue. Closing it now - feel free to reopen if the fix doesn't work for you.
