### ISSUE TITLE
No Window Title

### ISSUE THREAD

**Issue by bob111111111111111111** [thebracket/bracket-lib#129]
Hi, Sir; thanks for this great work.
I am learning Rust partly through your tutorial and I have a very basic question that I can not answer after some searching.
This bit of code:
```
use rltk::{Rltk, GameState};

struct State {}
impl GameState for State {
    fn tick(&mut self, ctx : &mut Rltk) {
        ctx.cls();
        ctx.print(1, 1, "Hello Rust World");
    }
}

fn main() -> rltk::BError {
    use rltk::RltkBuilder;
    let context = RltkBuilder::simple80x50()
        .with_title("Roguelike Tutorial")
        .build()?;
    let gs = State{ };
    rltk::main_loop(context, gs)
}
```
fails to display "Roguelike Tutorial" in the title bar.
Everything else works fine.
I am using Crostini (Linux on a Chromebook -- sort of Debian...).
What am I doing wrong?
Thanks.

**Comment by thebracket** [comment]
That's a really odd one, it works for me. Maybe it's a window manager issue? Which window manager (and back-end; X11 or Wayland) are you using?

If you're using Wayland, you may want to try X11. I've had no end of trouble with the `winit` support for Wayland, sadly.

**Comment by bob111111111111111111** [comment]
OK, thank you for the prompt response, and sorry for the delayed reply.
Keep up the good work!
Robert
