### ISSUE TITLE
ctx.quit() doesn't actually do anything?

### ISSUE THREAD

**Issue by RantingBob** [thebracket/bracket-lib#133]
https://github.com/RantingBob/escape-from-alpha-nine/blob/feature/entity-map-resource/src/systems/pre_update_systems/exit.rs

I have an exit system, with a BTerm saved into Specs resources using ctx.clone().  When I call ctx.quit() in the system it doesn't actually stop calling tick().  Currently I'm calling std::process::exit(0) but that doesn't call destructors and clean up clearly I believe.

**Comment by thebracket** [comment]
I tested it in a few examples, and `ctx.quit` called terminates the example. I think the problem you are running into is that you cloned `ctx` - so you're setting the "quitting" flag on the *clone*, not on a context that is actually visible to the library. You'll have similar problems writing to the console via a cloned context - the clone will update it's own cloned terminal data, so the engine won't see the changes.

The `tick` function receives a *reference* to a context. It's pointing at the actual context being used to handle engine functionality. Once you clone it, the clone is pointing to a perfect copy of the context - but not the one the engine knows about. So it doesn't do much at all. That's fine for reading input and similar, but you have to send "quit" messages and similar to the *actual* context - not the clone. I recommend using the "draw batch" system for rendering inside systems, it is designed to accomplish the same without busting Specs' ability to multi-thread your program or having to make context `sync+send` to store the reference as a resource.

**Comment by RantingBob** [comment]
Oh that’s perfect.

I’ll check it out this evening. Thank you.

**Comment by RantingBob** [comment]
Just so I can understand and make sure I'm doing this correctly, I could do something like this:

1. Create a list of map of console IDs (usize) set it as a resource
2. IN a given system create a DrawBatch with the target console retrieved from said map
3. Submit that drawbatch.  Therefore not having to clone the context into my systems.

For input, I can still clone hte context, is there another way to get that which doesn't require me to store the context?
