### ISSUE TITLE
Bresenham Line algorithm doesn't test all directions and fails going South East

### ISSUE THREAD

**Issue by joshuajbouw** [thebracket/bracket-lib#135]
Bresenham appears to work correctly on the Y axis but not on the X axis. I'm able to increment and decrement the Y axis but the X axis fails miserably.

Example:
```rust
let line = BresenhamLine::new(Point::new(0, 6), Point::new(6,0));
let res: Vec<Point> = line.collect();
```
res results with an empty vector because of `if self.x >= self.x1 {` check.

Is this is changed to `if self.x >= self.x1 && self.y >= self.y1`, with `y1` being the `end.y`, it results in the following vector:
```
[ 0, 6]
[-1, 5]
[-2, 4]
[-3, 3]
[-4, 2]
[-5, 1]
```

This might apply to move cordial directions.

**Comment by joshuajbouw** [comment]
From what I can tell this bit:
```rust
    fn with_point(&self, p: Point2<i32>) -> Point2<i32> {
        println!("self.0: {}", self.0);
        match self.0 {
            0 => Point2::new(p.x, p.y),
            1 => Point2::new(p.y, p.x),
            2 => Point2::new(-p.y, p.x),
            3 => Point2::new(-p.x, p.y),
            4 => Point2::new(-p.x, -p.y),
            5 => Point2::new(-p.y, -p.x),
            6 => Point2::new(p.y, -p.x),
            7 => Point2::new(p.x, -p.y),
            _ => unreachable!(),
        }
    }
```
Is wrong. i.e for this particular direction which is an octant of 4, it states this: `4 => Point2::new(-p.x, -p.y),` but it in fact should be `4 => Point2::new(p.x, -p.y),`

**Comment by thebracket** [comment]
I'm not sure about this one. If I modify the `bresenham_line.rs` example to use the coordinates from your first post, and display the resulting line numbered and as debug-print:

```rust
use bracket_geometry::prelude::*;
use crossterm::queue;
use crossterm::style::Print;
use std::io::{stdout, Write};

fn main() {
    let mut fake_console: Vec<char> = vec!['.'; 100];

    let line : Vec<Point> =  Bresenham::new(Point::new(0, 6), Point::new(6, 0)).collect();

    for (i,point) in line.iter().enumerate() {
        let idx = ((point.y * 10) + point.x) as usize;
        let character = 48 + i as u8;
        fake_console[idx] = character as char;
    }

    for y in 0..10 {
        let mut line = String::from("");
        let idx = y * 10;
        for x in 0..10 {
            line.push(fake_console[idx + x]);
        }
        line.push('\n');
        queue!(stdout(), Print(&line)).expect("Command fail");
    }
    stdout().flush().expect("Flush Fail");

    line.iter().for_each(|p| println!("{:?}", p));
}
```

I get the following:

```
..........
.....5....
....4.....
...3......
..2.......
.1........
0.........
..........
..........
..........
Point { x: 0, y: 6 }
Point { x: 1, y: 5 }
Point { x: 2, y: 4 }
Point { x: 3, y: 3 }
Point { x: 4, y: 2 }
Point { x: 5, y: 1 }
```

If I add a test to `line_bresenham.rs`, it passes:

```rust
#[test]
fn test_issue135_line() {
    let line = Bresenham::new(Point::new(0, 6), Point::new(6,0));
    let res: Vec<Point> = line.collect();
    assert!(res.len() == 6);
    res.iter().for_each(|p| {
        assert!(p.x >= 0);
        assert!(p.x < 7);
        assert!(p.y >= 0);
        assert!(p.y < 7);
    });
}
```

(Those are without changing the line code)

I see you are using `BresenhamLine` as a type, but that doesn't appear in the `bracket-geometry` library?

**Comment by thebracket** [comment]
I added some tests and a new "bresenham sweep" example that goes through all of the angles from 0..360 and it doesn't seem to fail?
![bresenham-sweep](https://user-images.githubusercontent.com/14896751/83424020-6e3a9400-a3f1-11ea-9d60-2b2074adf9ce.gif)

What am I missing?

**Comment by joshuajbouw** [comment]
Weird, we spoke about this a little bit privately. Its good to have the tests in. I took it out of context and may have missed something... Using bits and pieces of bracket-lib but admittedly should've tried it in the crate first. It should've been a direct copy though. I'll double check again when I can get around to it again. For now, can close this issue but thanks for putting in the time to add more tests.
