### ISSUE TITLE
Implement Serialize / Deserialize for RandomNumberGenerator

### ISSUE THREAD

**Issue by rodya-mirov** [thebracket/bracket-lib#137]
It would be nice if we could persist the state of the RandomNumberGenerator in a save file, to prevent save scumming. It's just a wrapper around XorShiftRng, which is (conditionally) de/serializable, so it shouldn't be a problem to do so.

**Comment by thebracket** [comment]
That's a good idea. I'll look into how the `rand` family stores the current working seed and see what I can do.

**Comment by rodya-mirov** [comment]
I think there's a simpler answer than that -- the RandomNumberGenerator is just a wrapper newtype around `XorShiftRng` which is serializable, so if you `[derive(Serialize, Deserialize)]` and put `[serde(transparent)]` both on your struct definition, you should be good to go.

https://serde.rs/container-attrs.html#transparent

**Comment by rodya-mirov** [comment]
jk you already got it 😅
