### ISSUE TITLE
Unresolved import in bracket-terminal for curses and crossterm backends

### ISSUE THREAD

**Issue by zaszi** [thebracket/bracket-lib#138]
Upon trying to compile bracket-terminal for the `curses` and `crossterm` backends, I'm getting the following error:

```
error[E0432]: unresolved import `crate::hal::VirtualKeyCode`
  --> /home/zaszi/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.1/src/lib.rs:51:13
   |
51 |     pub use crate::hal::VirtualKeyCode;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `VirtualKeyCode` in `hal`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `bracket-terminal`.

To learn more, run the command again with --verbose.
```

Due to a few conditional import statements in `bracket-terminal/lib.rs`:

```
    #[cfg(target_arch = "wasm32")]
    pub use crate::hal::VirtualKeyCode;

    #[cfg(feature = "curses")]
    pub use crate::hal::VirtualKeyCode;

    #[cfg(feature = "crossterm")]
    pub use crate::hal::VirtualKeyCode;
```

But despite those re-exports existing lower down and my IDE finding that path just fine, the compiler throws a fit. If I remove the lines everything works as expected for my particular project, but that doesn't look like the proper way to fix this.

**Rust version:** 1.43.1
**bracket-lib version:** 0.8.1

**Comment by thebracket** [comment]
I managed to replicate this. If you are using a back-end other than OpenGL, make sure you put `default-features = false` in your `Cargo.toml` include. I should try to add a warning to that.

**Comment by thebracket** [comment]
So to be more clear, this doesn't work with the error message you saw:
```
rltk = { version = "0.8.1", features = ["serde","crossterm"] }
```

This does work on my system:
```
rltk = { version = "0.8.1", default-features=false, features = ["serde","crossterm"] }
```

**Comment by zaszi** [comment]
I edited my Cargo.toml as per above and now everything works as expected. Thanks for clarifying.

Even though your README points out this requirement, it seems I made a bad edit at some point. The resulting error wasn't very clear as to what the problem actually was, so a custom error message might indeed help people running into this oversight.

**Comment by thebracket** [comment]
I've added a compilation error for this case now. Thanks!

**Comment by zaszi** [comment]
I tested this out a little, but can't seem to get the new error to show. In my Cargo.toml:

```
[dependencies]
#bracket-lib = { version = "0.8", default-features = false, features = ["specs", "serde", "threaded"] }
bracket-lib = { git = "https://github.com/thebracket/bracket-lib", features = ["curses"] }
```

But I still get the original error message in the OP, not your custom one. Despite running cargo clean, cargo update and verifying I'm on the latest commit of bracket-lib.

**Comment by zaszi** [comment]
After studying up on Cargo a bit more, it seems that once again the problem was on my end. Correctly overriding the bracket-lib dependency with the latest master branch does indeed show the new error. Thanks!
