### ISSUE TITLE
Screenshots don't seem to work

### ISSUE THREAD

**Issue by rodya-mirov** [thebracket/bracket-lib#145]
My code:

```
impl GameState for State {
    fn tick(&mut self, ctx: &mut BTerm) {
        self.update(ctx);
        self.render(ctx);
        if Some(VirtualKeyCode::P) == ctx.key {
            let filename = format!("./screenshot_{}.png", self.screenshot_idx);
            self.screenshot_idx += 1;
            ctx.screenshot(filename);
        }
    }
}
```

Expected: screenshot includes the whole screen:
Actual: screenshot is a seemingly random segment of the screen

Platform: Macbook Pro, macOS Catalina. I have a retina display on my laptop, so could have some relationship with DPI? I don't know a ton about rendering but if it somehow doesn't take into account scaling (or handles it twice, or something...) that could account for it.

I've attached some examples:

This one, I took with cmd+shift+4, and it seems to reflect the truth:
<img width="626" alt="Screenshot_Through_OS" src="https://user-images.githubusercontent.com/2120690/85186171-83267c80-b265-11ea-9da3-9a5b45912323.png">

This one, I took with the in-game code, and seems to be the right size but stretched out:
![screenshot_0](https://user-images.githubusercontent.com/2120690/85186187-a18c7800-b265-11ea-8cbe-de0937bbdd05.png)

**Comment by rodya-mirov** [comment]
Did a `cargo update` for the project, and several transitive dependencies of bracket updated, in particular, image. This seems to have fixed the issue, so I'm gonna call it good.

Love your library

**Comment by rodya-mirov** [comment]
Kidding, but narrowed it down -- it seems to work fine when I'm plugged into a monitor, but not when I'm on my laptop (disconnected). Could be related to retina screen?

**Comment by rodya-mirov** [comment]
This may be the same issue as https://github.com/thebracket/bracket-lib/issues/40

**Comment by thebracket** [comment]
I've confirmed that this is part of the dpi scaling issues I've been fighting. Testing a fix now.

**Comment by thebracket** [comment]
Screenshots worked for me now on Windows with and without scaling, and Ubuntu X11 & Wayland. So I think we're ok - please reopen if its still a problem.
