### ISSUE TITLE
No need for [patch.crates-io]

### ISSUE THREAD

**Issue by bjorn3** [thebracket/bracket-lib#149]
If you specify both `version` and `path` for a dependency, cargo will use `path` when building locally and `version` when publishing to crates.io.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

> It is possible to specify both a registry version and a git or path location. The git or path dependency will be used locally (in which case the version is ignored), and when published to a registry like crates.io, it will use the registry version. Other combinations are not allowed.

**Comment by thebracket** [comment]
Nice! I'll change that. Thanks!
I'm taking a short break from development (too much RL stuff going on) - I'll be back applying fixes very soon.

**Comment by thebracket** [comment]
I've applied a PR that took care of this.
