### ISSUE TITLE
bracket-lib forces x11 even on wayland and won't launch

### ISSUE THREAD

**Issue by Maxgy** [thebracket/bracket-lib#161]
There is a line in [`bracket-lib/bracket-terminal/src/hal/native/init.rs`](https://github.com/Maxgy/bracket-lib/blob/master/bracket-terminal/src/hal/native/init.rs) that essentially forces x11 backend for winit:
```rust
// Force Wayland to use X11, which actually works.
std::env::set_var("WINIT_UNIX_BACKEND", "x11");
```
The truth is that this doesn't work when running pure wayland. I use Sway WM with XWayland not installed and x11 completely disabled, and upon using the updated git version of bracket-lib, windows won't launch anymore and instead display the panic `Failed to initialize X11 backend` even with `WINIT_UNIX_BACKEND=wayland` set. This was of course due to bracket-lib manually changing the environment variable itself.

At first I thought it might just be a winit issue, but then I forked bracket-lib and commented out this line, and my project executed the window.

Is this line necessary in bracket-lib or could we just safely remove it? I'm also aware that not everything renders correctly in wayland yet (I've seen it).

**Comment by Maxgy** [comment]
I'm going to go ahead and probably make a pull request.

**Comment by thebracket** [comment]
I'll have to check to see if Wayland is still horribly broken via Winit before merging this in. The forced path was present because Wayland on Ubuntu was causing all manner of issues, and the issues seemed to come from Winit.
