### ISSUE TITLE
Compile issues when targeting aarch64-apple-darwin (Apple M1)

### ISSUE THREAD

**Issue by abowerman** [thebracket/bracket-lib#172]
Seeing a few of these when I try to compile on:

`Default host: aarch64-apple-darwin`

```
   Compiling winit v0.22.2
error[E0308]: mismatched types
   --> /Users/andrew/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/util/async.rs:170:55
    |
170 |                 ns_window.setFrame_display_(new_rect, 0);
    |                                                       ^ expected `bool`, found integer
```

It looks like winit `v0.23.0` fixes this https://github.com/rust-windowing/winit/pull/1752

**Comment by thebracket** [comment]
I'll see if I can get `winit` updated. Testing this one may be tricky, I don't have access to any Apple M1 devices on which to test.

**Comment by thebracket** [comment]
The current head has updated glutin & winit to 0.23. Anyone have an M1 to test this on?

**Comment by abowerman** [comment]
Yeah, checking

**Comment by thebracket** [comment]
Oh nice, thank you! I'll give that a shot.

**Comment by abowerman** [comment]
And Unfortunately I misunderstood, and this winit fix has made it into `master` not `0.23.0`. 

patching in the master branch works:

```toml
[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", branch = "master" }
```

but then I have an issue with glutin: 

```
   Compiling glutin v0.25.1
error[E0432]: unresolved import `winit::platform::desktop`
  --> /Users/andrew/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.25.1/src/platform/mod.rs:33:30
   |
33 |     pub use winit::platform::desktop::*;
   |                              ^^^^^^^ could not find `desktop` in `platform`
```

Will keep digging, let me know if this is unhelpful.

**Comment by thebracket** [comment]
If its in their master, I'll have to wait for winit to publish it - and for Glutin to update to use it. :-(

**Comment by cjbehm** [comment]
I pulled bracket-lib master and updated smallvec (per the open PR) and then updated glutin and winit to current released versions in bracket-terminal/Cargo.toml
```
glutin = {version = "0.26", optional = true }
winit = { version = "0.24.0" }
...
winit = { version = "0.24.0", features = [ "web-sys" ] }
```

Tested by pulling the rustrogueliketutorial tutorials and changing the tutorial Cargo.toml files to reference my bracket-lib/rltk. I didn't test all of the tutorials, but I tested chapter 01 and 68 which appeared to work correctly.

**Comment by rdamron** [comment]
Ran into this issue, it seems like winit has fixed the issue but maybe glutin doesn't know they need to update to fix it on M1's.

Either way, I am progressing with the book by compiling with x86 and letting rosetta2 run the app.
```
cargo run --target x86_64-apple-darwin
```

**Comment by thebracket** [comment]
A friend tells me that with the new glutin/winit it works for them. Anyone else mind testing for me, please?

**Comment by rdamron** [comment]
Happy to try, what's the best way to override the versions that ship with bracket-lib? Still new to the Rust toolchain.

**Comment by thebracket** [comment]
You should be able to replace the `bracket-lib` line `Cargo.toml` with:

```
[dependencies]
bracket-lib = { git = "https://github.com/thebracket/bracket-lib.git" }
```

That will download the latest github main, and build from there. It *should* work - `winit` is updated to not crash on the M1 chip now.

Thanks!

**Comment by rdamron** [comment]
Works wonderfully now! Thanks for the update to bracket-lib.

**Comment by thebracket** [comment]
Awesome, thank you! I'll get this issue closed, and I'm one step closer to shipping the next crate version.
