### ISSUE TITLE
Resolution changes when moving terminal window between monitors

### ISSUE THREAD

**Issue by mikecargal** [thebracket/bracket-lib#173]
I'm working through the examples in Hands-on Rust (hi Herbert!).

In trying to debug some typo I have somewhere, I moved the terminal window for the dungeon crawler app to another monitor (so I could view my println! output I'm using to debug).

Latest release of Mac OS (Big Sur).  5k iMac with 27" cinema display attached.  

When do a I run the app (from a terminal on the cinema display), the window looks like this on the Cinema display:

![Screen Shot 2020-11-23 at 8 32 56 AM](https://user-images.githubusercontent.com/2240827/99968648-67208d00-2d67-11eb-96a4-9f501bc21270.png)

But when I drag it to the 5k display, it changes to this (no resizing involved):
<img width="1392" alt="Screen Shot 2020-11-23 at 8 33 05 AM" src="https://user-images.githubusercontent.com/2240827/99968726-85868880-2d67-11eb-95f1-711262dee35c.png">

Out of curiosity, I moved the terminal to the 5k display and ran it.  

The app looks like this on the 5k display:

<img width="1348" alt="Screen Shot 2020-11-23 at 8 42 41 AM" src="https://user-images.githubusercontent.com/2240827/99969013-e44c0200-2d67-11eb-883d-8f3655d36bd0.png">

And like this when dragged to the Cinema display:

![Screen Shot 2020-11-23 at 8 43 27 AM](https://user-images.githubusercontent.com/2240827/99969081-fb8aef80-2d67-11eb-85d9-10cfa9297ff9.png)

It appears that resolution is being assessed from information obtained from the screen the app is started from (and it appears correctly there), but needs to be re-assessed when moved to another display.

Both screen resolutions are set to "Default for display". (Cinema display is 2560x1440)

**Comment by thebracket** [comment]
I really need to get a bigger monitor! It looks like I'll need to handle the "moved" event for the window and call the same resizing code post-move. I have three monitors, but they are all 1080p. I'll see if I can reproduce and fix this. Thanks!

**Comment by thebracket** [comment]
c5cd5bd seems to have fixed this on Windows. Setup a CRAZY situation with 3 monitors each on differing resolutions and display scales and dragged the `astar_mouse` example between them. After this fix, it behaved as intended.

**Comment by thebracket** [comment]
You indicated in the other thread that this is working now. :-) So I'm going to mark the ticket as "closed"; if the problem recurs, feel free to re-open this.
