### ISSUE TITLE
Make TextBlock not panic if full, or allow query if it is room

### ISSUE THREAD

**Issue by carlfindahl** [thebracket/bracket-lib#189]
**On Rust:** 1.49.0
**OS:** Arch Linux

Hi, I'm working with `TextBlock` to draw a log for a project I'm working on. I submit several `TextBuilders` to this to compose the 
visible log entries. However, the log has limited space defined by the block. The issue occurs when the text builders add text beyond the available space of the block. The program simply `panic!`'s with no reasonable way to recover as far as I can tell. I see three possible solutions:

1. Let me query the remaining size of the block to see if it can fit the text in the builder, ala: `TextBlock.can_fit(builder)`
2. Return a `Result<Ok, OutOfSpace>` from the `block.print(...)` so I can at least avoid the panic and handle it myself
3. Allow Text Block's to have an scroll region. This probably needs to work in union with the previous two

I can possibly try to do a PR if you are busy, but I would still like an opinion on which you prefer. Perhaps another option already exists that I don't know about (still new to `bracket`)? I couldn't find it in the documentation or by googling at least. If there are other options in `bracket_lib` that let me easily print multiple colors in the same string I'd be open to change my approach too.

Thanks for the great library!

**Comment by thebracket** [comment]
Sorry for slow replies, real-life has been hitting hard (I got ill, my mother ended up hospitalized - ack). Catching up now. I'll take a look at this now.

**Comment by thebracket** [comment]
I believe the patch I just posted will take care of your needs. Let me know if there's any issues with it. Thanks for reporting the panic!

**Comment by carlfindahl** [comment]
That worked great! Thanks for looking a it, hope you and your family are doing better! Appreciate your work on the library.
