### ISSUE TITLE
Rltk::mouse_pos() is incorrect with HiDPI

### ISSUE THREAD

**Issue by bofh69** [thebracket/bracket-lib#40]
I'm using version 0.5.15 and is calling Rltk::set_bg with Rltk::mouse_pos() as position. At first this follows the mouse pointer, but after I resize the window the mouse_pos position is no longer translated to the right position in console coordinate space.

**Comment by bofh69** [comment]
The issue remains with 0.5.17.

My window is 80 characters wide. The font has tile_size (8,8). Rltk::mouse_pos contains values in the range 0..1280 since I'm using HiDPI. Rltk::width_pixels is 1280 as well.

Perhaps a better implementation of mouse_pos() would be: mouse_pos * get_char_size() / (width_pixels, height_pixels) ?

**Comment by bofh69** [comment]
I was a bit too fast there. No, the issue doesn't remain, it is now always incorrect even before resizing.

**Comment by thebracket** [comment]
I merged in some HiDPI fixes that included the mouse, this morning. It works on my Win10 laptop when I manually set scaling (I don't have anything that natively uses it). Any chance you could give it a test, please?

**Comment by NielsRenard** [comment]
Tested it out on Ubuntu 18.4, x11, 2560x1440 resolution
When display scale is set to 200% (which is what I usually use) this behaviour is shown:
![high-dpi-screen](https://user-images.githubusercontent.com/34090207/72852426-d1087a00-3cf1-11ea-956e-140acc1460ec.gif)

With display scale at 100% the mouse position is correct.
![high-dpi-screen-unscaled](https://user-images.githubusercontent.com/34090207/72852599-6572dc80-3cf2-11ea-8d2f-2dd208f16f45.gif)

The mouse position issue I was having on a regular screen are fixed with last update it seems.

**Comment by thebracket** [comment]
I'll give this another go. Tagging as "help wanted", because I don't seem to have a lot of luck with it!

**Comment by thebracket** [comment]
Here's a fun bug, and I'm not sure it's my fault! On my Ubuntu VM, I launch Ubuntu on Wayland. Set the display scale to 150%. Querying `wc.window().scale_factor()` from `winit` gives an answer of 2.0.
That would be a problem.

**Comment by thebracket** [comment]
This is actually turning into quite the bundle of bugs, so I'm opening a branch to work on it (`issue-40-hidpi`). I think I'll be sending some bug reports upstream, also.

On Ubuntu-Wayland with 200% scaling set:

- The scale factor from `window.scale_factor()` returns `2.0` - correct.
- The "physical position" returned from `WindowEvent::CursorMoved` goes 0..640.
- The "physical size" returned by `window.inner_size()` is 1280 (but still a `Physical` type!)
- If you try and convert the physical position to logical (since it's obviously not really physical), it changes the range to 0..320 - *the wrong direction*.

On Ubuntu-Wayland, multiplying the `x` and `y` by the scale factor works. Doing that on Windows 10 breaks everything if your scale factor isn't 1.0, because the mouse position is actually scaled on that platform. I haven't tried a Mac.

**Comment by NielsRenard** [comment]
I can help by testing things on my high dpi screen. No idea how hard this stuff is to get up to speed with from zero, but I'll check out that branch.

**Comment by thebracket** [comment]
I've currently got it scaling properly on Linux, which broke scaling on Windows 10. Ugh.

**Comment by thebracket** [comment]
It looks like there's a bug report referencing this behavior: https://github.com/rust-windowing/winit/issues/1406

**Comment by NielsRenard** [comment]
Can confirm that issue-40-hidpi branch works on wayland, with both 200% and 300% scaling.

However: On X11 the behaviour is now the opposite of yesterdays gif's. New gif incoming, 1 sec.

**Comment by NielsRenard** [comment]
![x11-40-high-dpi-200scaled](https://user-images.githubusercontent.com/34090207/72918007-3174d700-3d45-11ea-8855-9fd0082bcece.gif)

**Comment by thebracket** [comment]
It's broken on Windows 10, too - I pushed that to see what happens if I make it work on Wayland, and the answer is "everything else breaks". :-|

**Comment by thebracket** [comment]
The answer from the `winit` folks is that it's fixed in their Github master (in issue https://github.com/rust-windowing/winit/pull/1385 ). So I may just have to wait for Glutin to pick that up.

**Comment by thebracket** [comment]
Apparently, I can patch the transitive dependency - so down that rabbit hole I go.

**Comment by thebracket** [comment]
The most recent push to the branch seems to be working on Win10 and Wayland (via VM) for me.

**Comment by NielsRenard** [comment]
![x11-40-high-dpi-200scaled-working](https://user-images.githubusercontent.com/34090207/72923924-41de7f00-3d50-11ea-9e11-7985b21053e7.gif)
bingo!

**Comment by NielsRenard** [comment]
That was X11, let me double check (non VM) wayland as well...

**Comment by thebracket** [comment]
Thanks! (Awesome gif recorder, by the way). Looks like I have an ice storm incoming, so I'm going offline for a bit.

**Comment by NielsRenard** [comment]
Hate to tell you, but wayland is now 'off' again for me. Tried it on two different ubuntu machines.
  
Behaviour is like yesterday: https://github.com/thebracket/rltk_rs/issues/40#issuecomment-576938169

**Comment by NielsRenard** [comment]
Otsukaresama desu! Thanks for working on this so far.  I run X11 so I'll stick on this branch for a bit.
(The gif recorder is called Peek https://github.com/phw/peek)

**Comment by thebracket** [comment]
So I've got it working reasonably well on my X11 and Win10 setups, but Wayland is causing nothing but headaches. 

* If I request a 640x400 window, it *instantly* sends me a "resize" event telling me that the window is really 640x370 - which it isn't, if you measure the window.
* Despite swearing blind that the window is 640x370, it still sends me mouse positions scaled from 0..400 on the Y axis!
* If I manually query the `inner_size` of the window, I get 640x370. If I manually query the `outer_size`, it gives the same answer! So BOTH are wrong.

Ugh. "Use X11" is my best advice currently.

**Comment by NielsRenard** [comment]
New ubuntu LTS is shipping in a couple months, has X11 by default still. No idea if many people are using Wayland.

I'm curious if it works on macOS as well now. (No way to test though).

**Comment by thebracket** [comment]
I have a Mac VM (it's extremely slow), I'll look. I just found out that if you disable window decorations, Wayland works ok - but I'm not sure I'd want to tell people "you don't need a minimize button".

**Comment by NielsRenard** [comment]
The changes on this branch fix the hidpi issues I have on X11, but this branch is getting stale compared to master. Would it be smart to merge and then open a new issue specifically for Wayland?

**Comment by thebracket** [comment]
I've merged Master back into the issue-40 branch, which should make it "un-stale". Since Wayland seems to be the only blocking issue on that branch, I'll see about ensuring *everything else* is in the master branch today, then we can bring this down to "Wayland is broken".

**Comment by thebracket** [comment]
Alright, if you *aren't* using Wayland, *MASTER* should now have the fixes from the issue_40 branch in it - OTHER than the physical/logical snafu that is awaiting a `winit` update.

**Comment by thebracket** [comment]
Ignore that last commit. I typed the wrong issue number in my commit message and pushed before I realized my error. Sorry.

**Comment by NielsRenard** [comment]
> Alright, if you _aren't_ using Wayland, _MASTER_ should now have the fixes from the issue_40 branch in it - OTHER than the physical/logical snafu that is awaiting a `winit` update.

👍 I'm back on master, works like a charm on ubuntu 18.4, x11, 2560x1440 resolution with scaling 200%. If I can help out with more testing in the future just @ me.

**Comment by WanderHog** [comment]
I'm having this issue on a 2019 MacBook Pro running 10.15.2. Changing display scaling doesn't seem to affect it in any way.

**Comment by thebracket** [comment]
That's not good (Mac is the platform I have the hardest time testing); it's working on Windows and X11 for me, even changing display scaling while running. Would you mind trying on master/head, and seeing if `cargo run --example ex06-astar-mouse` gives you correct mouse positions, please?

**Comment by WanderHog** [comment]
I actually tried this the other day and it's a weird one.

![stuff](https://user-images.githubusercontent.com/60977741/74563954-84e8d800-4f33-11ea-8112-cf9bbfbbfe61.gif)

It's seems to be reading it properly at first, but after resizing the window to fix the display it reverts back to being goofed out? I honestly thing it has something to do with the way Apple does display scaling. It doesn't seem like they scale the resolution at all like windows does, it just scales text and textures up. I'd test it on my windows machine but winit has compiling screwed up on that right now with some kind of dark mode bug. I'm really not 100% sure what's going on with the Mac stuff, but I'd be happy to try out whatever and help you test if you want to try to figure it out.

**Comment by WanderHog** [comment]
Update, started goofing around, just changed from Glutin 0.22.0 to 0.23.0 and it completely fixed it. I assume you'll want to make sure nothing changed that will make anything buggy, but it 100% solves the mouse issue on MacOS.

**Comment by hammerandtongs** [comment]
So on X11 AMD gpu(and Intel gpu) Ubuntu 18.04 without hi-dpi monitor I have the same behavior as shown in the gif 

https://github.com/thebracket/rltk_rs/issues/40#issuecomment-577297384

I'm pulling from master atm but 0.6.2 has same behavior now. This is odd as it was not occurring a few days ago and now...

**Comment by thebracket** [comment]
The most recent fixes should take care of this. I'm currently getting correct `mouse_pos()` on all the platforms I have available to test, on various DPI settings. Tested on: Windows (with 100%, 125%, 150%, 200%), Ubuntu/X11 (with 100% and 200%), Ubuntu/Wayland (100% and 200%). I'm hoping someone with a Mac can verify this for me.

**Comment by thebracket** [comment]
A friend with a Mac tells me that this is resolved. :-)

**Comment by thebracket** [comment]
I've now had two reports that this is ok, so I'm closing this issue. Please feel free to re-open if it bites you again.
