### ISSUE TITLE
Background color is ignored

### ISSUE THREAD

**Issue by vojta7** [thebracket/bracket-lib#53]
Version 6.0.0

The background color is not being displayed when compiled for wasm32. I am using Rltk::init_simple8x8 and method set(x,y,fg,bg,glyph) (basically code from your tutorial). When compiled for native target everything works fine.

Is background color unsupported for wasm32, or is this bug?

**Comment by thebracket** [comment]
That sounds like a bug; I'll see what I can do to reproduce it. The shaders for WASM ended being a little funky, so I probably missed something (the longer term plan is that when Amethyst works with WASM, I'll be using it as a default back-end. They write much better graphics code than I do!)
