### ISSUE TITLE
Layered tiles dont work.

### ISSUE THREAD

**Issue by Gaunsessa** [thebracket/bracket-lib#78]
When I try using multiple layers the background stays black this problem occurs even when I try to build the examples 7 and 18. 
![image](https://user-images.githubusercontent.com/43172308/75244591-2586a400-5820-11ea-8db9-2b4838194dd0.png)
I am on windows 10 with rust 1.43.0-nightly and using version 7.0.0 of rltk.

**Comment by thebracket** [comment]
Good catch! I goofed on the initialization - it was meant to call `with_sparse_console_no_bg`. Thanks!
