### ISSUE TITLE
crossterm: Terminal's state not always reset on exit

### ISSUE THREAD

**Issue by spenserblack** [thebracket/bracket-lib#80]
When running examples with the crossterm feature enabled, I found that the cursor remains hidden and mouse capture remains enabled sometimes after exit. It might be a good idea to add panic hooks and/or signal hooks to make it more likely that the terminal's state is reset on exit. Entering/exiting an alternate terminal might also work.

**Comment by thebracket** [comment]
I didn't implement a signal handler (the docs are confusing on that one), but I added a panic handling hook. It worked with a variety of ways to kill my process on Windows; I haven't tested on Linux yet.

**Comment by spenserblack** [comment]
[Setting a flag on SIGINT](https://docs.rs/signal-hook/0.1.13/signal_hook/flag/index.html#functions) might do it. But, thinking about it more, that might be unnecessary, and instead left up to the user to break the game loop on `ctrl`+`c` (preferably, anyone playing a game shouldn't have to press `ctrl`+`c` to kill it, though :laughing: ).

I did find your note [here](https://github.com/thebracket/bracket-lib/blob/master/bracket-terminal/src/hal/crossterm_be/main_loop.rs#L62). This doesn't seem to be the case on Linux. At least, as a quick test, I put an `eprintln!` in the `ctrl`+`c` capture there, redirected STDERR to a file, and didn't find my `eprintln!` message in the file.

Thanks for adding the panic hook!

**Comment by thebracket** [comment]
Alright, with those fixes hitting `ctrl+c` on my Linux test setups exits correctly and leaves the terminal a usable state.

**Comment by spenserblack** [comment]
Awesome! Just ran it on my machine as well, and can confirm that <kbd>Ctrl</kbd>+<kbd>c</kbd> works much better after commits 05c4afb and 03ae0f1.
