### ISSUE TITLE
screen not updated if ctx.cls() is not called

### ISSUE THREAD

**Issue by jice-nospam** [thebracket/bracket-lib#82]

**Comment by thebracket** [comment]
I found a few places that `is_dirty` wasn't being set properly (mostly on primitives like `set`; the higher-level ones seemed ok). So I fixed that, fixed it for a couple of scaling/offset commands that basically nobody uses, and added a `no_cls` example to act as a test case.

**Comment by jice-nospam** [comment]
works!
