### ISSUE TITLE
Dice parsing ignores signs and whitespace separated constants.

### ISSUE THREAD

**Issue by Monadic-Cat** [thebracket/bracket-lib#85]
I tested the `bracket-random` crate as follows:
```rs
use bracket_random::prelude::*;

fn main() {
    let mut rng = RandomNumberGenerator::new();
    println!("Results: {}", rng.roll_str(/* dice expression here */).unwrap())
}
```
Here are some bad cases:
```
"9d8 + 5000" // Example result: 46
```
```
"9d8 - 40d10" // Example result: 176
```
I tested with longer expressions and with different signs.
The parser appears to ignore negative signs when space separated, but not when all spaces are omitted.
It appears to ignore constants when space separated, but not when all spaces are omitted.
Note that "space separated" here means that just one space needs to be included to produce these invalid results.
(EDIT: typo)

If you want a quick fix, stripping all the whitespace from the input string before applying your regex to it looks like it should work.
(For an example of what I hope is a bit better approach, see the slightly messy parser in my dice rolling crate: https://github.com/Monadic-Cat/mice/blob/master/src/parse.rs)

**Comment by thebracket** [comment]
I've added a unit test and merged the PR. It's passing whitespace tests now. Thank you so much!
