### ISSUE TITLE
'index out of bounds' error in SparseConsole.set_bg()

### ISSUE THREAD

**Issue by imoea** [thebracket/bracket-lib#90]
The following gives an `index out of bounds` error because a sparse console's `self.tiles.len()` is often a lot smaller than a simple console's, and `idx` in this case is with respect to the latter.

https://github.com/thebracket/bracket-lib/blob/9a4d7fe31140d47fcc983bb515929b85c3ce2aa3/bracket-terminal/src/sparse_console.rs#L129-L134

**Comment by thebracket** [comment]
Good catch, thank you! That's a bug - it's meant to push to the tile list, rather than referencing it. I'll have a fix up in a moment.
