### ISSUE TITLE
offset in draw_box background with amethyst-vulkan renderer

### ISSUE THREAD

**Issue by jice-nospam** [thebracket/bracket-lib#93]
Running the benchmark example with amethyst-vulkan renderer results in a vertical offset in the background of the box :
```rust
ctx.draw_box(
            30,
            20,
            20,
            5,
            RGB::from_u8(255, 255, 255),
            RGB::from_u8(0, 0, 0),
        );
```
```shell
cargo run --no-default-features --features=amethyst_engine_vulkan --example benchmark --release
```
![amethyst](https://user-images.githubusercontent.com/7805711/75616424-e1154400-5b50-11ea-9bd4-496716ebb718.png)

```shell
cargo run --example benchmark --release
```
![native](https://user-images.githubusercontent.com/7805711/75616427-e4103480-5b50-11ea-8213-7700b69fa4c0.png)

**Comment by thebracket** [comment]
I'm not currently able to replicate this. I think it got fixed as part of another bugfix (I had some issues with part of the Amethyst terminal being upside-down)? I did just fix Amethyst compilation on the latest changes.

I'll go ahead and close this - please reopen if it is still an issue and I'm missing something.
