### ISSUE TITLE
amethyst renderer does not respect with_vsync(false)

### ISSUE THREAD

**Issue by jice-nospam** [thebracket/bracket-lib#94]
I tried to update the amethyst main loop with this code but it's still stuck at 60 fps :

```rust
    let vsync = {
        let be = BACKEND.lock().unwrap();
        be.platform_hints.vsync
    };
    let mut builder = Application::build(
        assets_dir,
        BTermGemBridge {
            bterm,
            state: Box::new(gamestate),
            key_delay: 0.0,
        },
    )
    .expect("Failed to make game data");
    if !vsync {
        builder = builder.with_frame_limit(FrameRateLimitStrategy::Unlimited, 0);
    }
    let mut game = builder.build(game_data).expect("Failed to make game data");
    game.run();
```

**Comment by thebracket** [comment]
That's something I'm struggling with. Amethyst has two layers of frame rate limiting (vsync and an actual limiter), and I've been having a heck of a time getting the two to adjust together!

**Comment by thebracket** [comment]
I just chatted with one of the Amethyst devs, and the vsync option isn't there anymore. Vulkan doesn't really have vsync - it has present modes, and currently they aren't externally configurable!

**Comment by jice-nospam** [comment]
Ok I guess I'll have to be smarter and not rely on the framerate to measure performance :) I'll see how to update the perf example to have some fairly relevant value. Shall I close this issue?

**Comment by thebracket** [comment]
Sadly, it's probably best to close it until Amethyst figure out what they want to do with this one.
