### ISSUE TITLE
Weird definition of Rect

### ISSUE THREAD

**Issue by imoea** [thebracket/bracket-lib#96]
I've been having trouble getting used to the definition of Rect here. Should a rectangle of size 1x1 contain 4 points? (I think it should only contain 1.)

https://github.com/thebracket/bracket-lib/blob/8d95aefa3ae8dc7d5636721c4cf2eb709a7f59d2/bracket-geometry/src/rect.rs#L169-L176

I'm thinking that the following shouldn't include the right boundary points.

https://github.com/thebracket/bracket-lib/blob/8d95aefa3ae8dc7d5636721c4cf2eb709a7f59d2/bracket-geometry/src/rect.rs#L77

https://github.com/thebracket/bracket-lib/blob/8d95aefa3ae8dc7d5636721c4cf2eb709a7f59d2/bracket-geometry/src/rect.rs#L85-L86

https://github.com/thebracket/bracket-lib/blob/8d95aefa3ae8dc7d5636721c4cf2eb709a7f59d2/bracket-geometry/src/rect.rs#L95-L96

Or is there a fundamental reason it was defined as so? The only reason I can think of is not being able to draw a zero-sized rectangle.

**Comment by imoea** [comment]
I'm willing to make the required changes in a pull request if it's not your top priority right now. With your approval.

**Comment by OliverUv** [comment]
There's a lot of bikeshedding one can do in geometry libraries, e.g. in my project I use my own
```
struct Rect {
    upper_left: Point,
    lower_right: Point,
}
```

but ... it's just bikeshedding. Any change should have a very good motivation since it would either break the API or cause a bunch of extra maintenance.

**Comment by imoea** [comment]
There are two things I feel should be important in any API: consistency and convention.

### Consistency

`BTermBuilder.simple80x50()` builds a 80x50 console and everything is drawn within that box as expected. `Rect::with_size(0, 0, 80, 50)` however, if fed straight into the `draw_box()` or `fill_region()` function, draws a box that occupies a 81x51 area. It's neither 80x50 with or without its borders. So if requires extra cognitive load when using `Rect`.

This problem becomes even more pronounced when using `Rect` for non-box-drawing purposes such as bounding boxes. The current implementation actually adds one to both width and height of the bbox when checking for intersections. This behaviour cannot be predicted or accounted for unless one draws it for verification or checks the source code to understand it's implementation.

I assume that `Rect` was first created with map generation in mind (I first saw it being used for that purpose in bracket's Rust roguelike tutorial [_thank you sir for teaching me Rust_]), but even so, a `Rect::with_size(0, 0, 4, 4)` only creates a 3x3 room.

### Convention

This is self-explanatory. Since Rust is 0-indexed, the convention is for a 80x50 box to occupy indices `0 <= x < 80`, `0 <= y < 50`, excluding the right-hand bounds. People coming in from other languages or libraries would expect it to behave this way as is the convention.

I hope this gives sufficient motivation or justification for the proposed changes. I understand that it might break many map generation algorithms, including those used in the tutorials. But I also feel that this is not a quirk every adopter of this library should have to deal with and eventually get used to either (this is coming from an active user's perspective).

I also understand that bracket has a lot more important things on his plate right now with the backend stuff, which is why I'm offering to make the necessary changes as a contributor. If bracket disagrees on the changes then I'll quietly close this issue and move on.

(I've thought of just implementing my own struct and not making a big fuss out of this but `fill_region()` still takes in a `Rect` as input. Unless I draw it myself with `set()`.. Hmm, now that's an idea..)

**Comment by imoea** [comment]
Here's an interim solution I'm using which works nicely with `bracket-lib`.

Both `(x1, y1)` and `(x2, y2)` are within the bounding box (upper-left and bottom-right). Because of this, comparisons are easy as they are strictly exclusive, i.e., see `contains()` and `intersects()`. `to_rect()` allows you to draw it with `bracket-terminal` and get what you'd expect.

If breakage to the current codebase and tutorials is a real concern, just adding this to the library (with some proper definitions, of course) could be a simple solution with no fixing required.

```rust
use bracket_geometry::prelude::{Point, Rect};

pub struct BBox {
    pub x1: i32,
    pub y1: i32,
    pub x2: i32,
    pub y2: i32,
    pub w: i32,
    pub h: i32,
}

impl BBox {
    pub fn with_size(x: i32, y: i32, w: i32, h: i32) -> Self {
        Self { x1: x, y1: y, x2: x + w - 1, y2: y + h - 1, w, h }
    }

    pub fn with_exact(x1: i32, y1: i32, x2: i32, y2: i32) -> Self {
        Self { x1, y1, x2, y2, w: x2 - x1 + 1, h: y2 - y1 + 1 }
    }

    // checks if it contains a point
    pub fn contains(&self, p: Point) -> bool {
        !(p.x < self.x1 || p.x > self.x2 || p.y < self.y1 || p.y > self.y2)
    }

    // checks if it intersects another bounding box
    pub fn intersects(&self, b: BBox) -> bool {
        !(b.x1 > self.x2 || b.x2 < self.x1 || b.y1 > self.y2 || b.y2 < self.y2)
    }

    // returns its centre
    pub fn center(&self) -> Point {
        Point::new((self.x1 + self.x2) / 2, (self.y1 + self.y2) / 2)
    }

    // returns a Rect (for drawing using bracket-terminal)
    pub fn to_rect(&self) -> Rect {
        Rect::with_exact(self.x1, self.y1, self.x2, self.y2)
    }
}
```

**Comment by OliverUv** [comment]
Your point about consistency is good! I am not opposed to such a change.

**Comment by workingjubilee** [comment]
At first this seemed like a quibble, but now that everything's laid out I agree. RLTK seems to value intuitive interfaces highly, e.g. `bracket-random` exists precisely to provide a more natural-seeming interface to random numbers even though plucking random values from a range works fine in Rust (it just isn't very "D&D"), so that developers have a more intuitive syntax. But I don't know anyone who would find the `Rect::with_size(0, 0, 80, 50)` -> 81x51 box example intuitive, so even if it is a breaking change it should be fixed.

**Comment by thebracket** [comment]
I'm actually not too attached to the `Rect` implementation. The tutorial uses its own version; this one is there for times you actually want to describe a rectangle for rendering, for clipping, and for a GUI library I'll release when it actually does something useful (think Turbo Vision style). So changing it isn't a big deal.

I *think* I got it updated. I'm coming off of a huge, multi-week 14-hour day crunch at work (thanks to everyone working from home, those of us who manage an ISP are stuck working hard!) - so I may have missed something.
